//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.5
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_QN3z51QE0"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "4na1ga9du6e5ljfn78a9p1q3td"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .USEast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "1f5h9n7lrci1o7q89dlck62s2qmkc1mfrc4d9a73ge2qhtdl0vfd"


