//
//  UserPoolNewPasswordViewController.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.5
//
//

import Foundation
import AWSCognitoIdentityProvider
import AWSMobileHubHelper

class UserPoolNewPasswordViewController: UIViewController {
    
    var user: AWSCognitoIdentityUser?
    
    @IBOutlet weak var confirmationCode: UITextField!
    @IBOutlet weak var updatedPassword: UITextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    
    @IBAction func onUpdatePassword(sender: AnyObject) {
        guard let confirmationCodeValue = self.confirmationCode.text where !confirmationCodeValue.isEmpty else {
            UIAlertView(title: "Password Field Empty",
                        message: "Please enter a password of your choice.",
                        delegate: nil,
                        cancelButtonTitle: "Ok").show()
            return
        }
        //confirm forgot password with input from ui.
        self.user?.confirmForgotPassword(confirmationCodeValue, password: self.updatedPassword.text!).continueWithBlock({[weak self] (task: AWSTask) -> AnyObject? in
            guard let strongSelf = self else { return nil }
            dispatch_async(dispatch_get_main_queue(), { 
                if let error = task.error {
                    UIAlertView(title: error.userInfo["__type"] as? String,
                        message: error.userInfo["message"] as? String,
                        delegate: nil,
                        cancelButtonTitle: "Ok").show()
                } else {
                    UIAlertView(title: "Password Reset Complete",
                        message: "Password Reset was completed successfully.",
                        delegate: nil,
                        cancelButtonTitle: "Ok").show()
                    strongSelf.presentingViewController?.presentingViewController?.dismissViewControllerAnimated(true, completion: nil)
                }
            })
            return nil
        })
    }
    
    @IBAction func onCancel(sender: AnyObject) {
        self.presentingViewController?.presentingViewController?.dismissViewControllerAnimated(true, completion: nil)
    }
    
}
